# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates

version: 2
updates:
- package-ecosystem: maven
  directory: /
  schedule:
    interval: weekly
  ignore:
    # ignore any Maven artifacts - those are provided!
    - dependency-name: "org.apache.maven:*"
    - dependency-name: "org.apache.maven.plugin-tools:*"
    # ignore maven-plugin-plugin - will be managed manually!
    - dependency-name: "org.apache.maven.plugins:maven-plugin-plugin"
    # ignore Maven invoker - will be managed manually!
    - dependency-name: "org.apache.maven.shared:maven-invoker"
    # ignore versions-maven-plugin - will be managed manually!
    - dependency-name: "org.codehaus.mojo:versions-maven-plugin"
    # ignore commons-lang3 - will be managed manually!
    - dependency-name: "org.apache.commons:commons-lang3"
    # ignore commons-text - will be managed manually!
    - dependency-name: "org.apache.commons:commons-text"
    # ignore plexus-interactivity-api - will be managed manually!
    - dependency-name: "org.codehaus.plexus:plexus-interactivity-api"
    # ignore tycho-versions-plugin - will be managed manually!
    - dependency-name: "org.eclipse.tycho:tycho-versions-plugin"
    # ignore guava - will be inherited from cdi-utils
    - dependency-name: "com.google.guava:guava"
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
