google_site_verification: YlVT2JQ5mn390epgBzUbxKe9-fDvVzLAGy-XUb1fS4M
plugins:
  - jekyll-relative-links
  - jemoji
  #- jekyll-sitemap
relative_links:
  enabled: true
  collections: true
include:
  - README.md
markdown: GFM
#theme: jekyll-theme-tactile
theme: jekyll-theme-slate
